#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

// DamageType
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DamageType_Blunt);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DamageType_Slashing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DamageType_Crushing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DamageType_Explosion);

// Element
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Element_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Element_Water);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Element_Ice);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Element_Electric);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Element_Wind);

// Material
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material_Wood);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material_Steel);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material_Bone);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material_Stone);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Material_Ancient);

// Monster

// 모코블린
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Monster_Goblin);
// 리자드맨
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Monster_Lizardman);
// 라이낼
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Monster_Centaur);
// 히녹스
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Monster_Ogre);